// <auto-generated />
using Ambev.DeveloperEvaluation.ORM;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Ambev.DeveloperEvaluation.ORM.Migrations;

[DbContext(typeof(DefaultContext))]
[Migration("20260813130000_AddSales")]
public partial class AddSales
{
}
